### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by Blaiserman** [rendicott/pySser#10]
```
 python pysser.py --hel
Traceback (most recent call last):
  File "pysser.py", line 22, in <module>
    import loaders
ImportError: No module named loaders
```

**Comment by rendicott** [comment]
Have you made sure the `loaders.py` is in the same directory? I believe you have to run the `pysser.py` script from the cloned directory so it has access to all the dependencies.

**Comment by rendicott** [comment]
Let me know if you need anymore help. For now I'm gonna close the issue.
