### ISSUE TITLE
blocking requierement 

### ISSUE THREAD

**Issue by gilcot** [rendicott/pySser#2]
Hello,

Under _Debian 7_ with all updated packages, a `pip install pySser` fails. :-( 
When looking at the source here, it appears that the `requieremet.txt` file mentions `requests==2.7.0` whereas my box use version `2.13.0` today.

**Comment by rendicott** [comment]
yeah, I don't have pySser in pypi yet. Not sure if there's enough demand. You can do a `pip uninstall requests` and then a `pip install -I requests==2.10.0` to fix that. Maybe set it up in a docker or virtualenv so you don't mess up your requests 2.13.0 environment.

**Comment by gilcot** [comment]
Hello R.

Thanks for yor reply. 
I downloaded the [`master.zip` from here](https://github.com/rendicott/pySser/archive/master.zip), unarchived it then removed the guilty file and added a [minimal `setup.py` in the parent directory](https://python-packaging.readthedocs.io/en/latest/minimal.html#creating-the-scaffolding), and finalemant `pip install <the/parent/directory>` voila. 

Just read your note on august 15. So what do I have to check for? So we can see if the problem is solved with this version of `Requests`  (if not, then I'll go your suggestion of either `docker` or `virtualenv`)

Regards.

**Comment by gilcot** [comment]
Hello,

You were right, it wasn't easy to make it work with _Requests_ version greater than 2.10.0 but I manage to do it after rewriting some lines. It's a known problem that won't be fixed as the way it was working was buggy and never documented to work so (read [issue 73477](https://github.com/kennethreitz/requests/issues/3477) and [issue 3512](https://github.com/kennethreitz/requests/issues/3512) for example) To fix it, just ensure that extra headers are strings...

**Comment by gilcot** [comment]
Hello,

I forgot, also missing from the `requirement.txt` the need of `configparser` (it wasn't in my install and is neither in default `virtualenv` as `--no-site-packages` is default behavior since 1.7)

**Comment by gilcot** [comment]
Commit 329cc77 correct this issue ; closing then.
