### ISSUE TITLE
values (subnet and hostname descriptions) with accents

### ISSUE THREAD

**Issue by gilcot** [rendicott/pySser#3]
Hello, 

I tried a `python pysser -c config.ini --filtersubnet=172.10.36.0` and had an error saying: 
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)

The error comes from line 89 in `Subnet` class. After some googling, the culprit seems to be [the use of `str` here](http://stackoverflow.com/a/9942822) I've changed that line to ` values.append(getattr(self, attr).encode('utf-8')) ` but had another error about NoneType not having attribute :( I then tryied [a workaround](http://stackoverflow.com/a/34570099) but not sure it's the right way to go:
```python
		if getattr(self, attr) is not None:
                        values.append(getattr(self, attr).encode('utf-8'))
		else:
		        values.append(u' ')
```

There's no more error, but no result shown either. However, adding a ` -d DEBUG ` to my initial command show that the subnet asked for is retrieved. 

Any help welcome. 

![problem_accents](https://cloud.githubusercontent.com/assets/27341580/25183825/f7cbc758-2518-11e7-85b7-c0fbb38ba1df.PNG)
![problem_nonetype](https://cloud.githubusercontent.com/assets/27341580/25183839/00af0862-2519-11e7-8b86-bc472bc10d77.PNG)
![problem_unshown](https://cloud.githubusercontent.com/assets/27341580/25183864/11b443ca-2519-11e7-839a-2e427c533d08.PNG)

**Comment by gilcot** [comment]
Hello,

Me back. I don't know yet why there's no output. However, i've been able to catch where the NoneType attributes are coming from. 

In a previous workaround, I put a one-space string where there's a missing attribute...
```python
        msg = ''
        attributes = []
        values = []
        for attr in dir(self):
            if (
                    '__' not in attr and
                    'instancemethod' not in str(type(getattr(self, attr))) and
                    'dict' not in str(type(getattr(self, attr))) and
                    'dump_ignore_attrs' not in attr):
                attributes.append(attr)
		# http://stackoverflow.com/a/34570099
		if getattr(self, attr) is None:
			values.append(u' ')
		else:
			# http://stackoverflow.com/a/9942885
                	values.append(getattr(self, attr).encode('utf-8'))
                # msg += (fmt.format(attr,getattr(self,attr)))
        format_helper = TableFormat(attributes, values, self.dict_extend_values, self.dump_ignore_attrs)
        msg += format_helper.string_header
        return msg
```

Later I try to avoid records that have missing attribute... 
```python
        msg = ''
        attributes = []
        values = []
        for attr in dir(self):
            if (
                    getattr(self, attr) is not None and
                    '__' not in attr and
                    'instancemethod' not in str(type(getattr(self, attr))) and
                    'dict' not in str(type(getattr(self, attr))) and
                    'dump_ignore_attrs' not in attr):
                attributes.append(attr)
		# http://stackoverflow.com/a/34570099
		# http://stackoverflow.com/a/9942885
                values.append(getattr(self, attr, u' ').encode('utf-8'))
                # msg += (fmt.format(attr,getattr(self,attr)))
        format_helper = TableFormat(attributes, values, self.dict_extend_values, self.dump_ignore_attrs)
        msg += format_helper.string_header
        return msg
```

Dumping both results with `-d DEBUG` it appears, when diffing both logs, that some fields are set to null because not filled for folders... 
![dd](https://cloud.githubusercontent.com/assets/27341580/25187453/5a11636e-2523-11e7-8229-12a824ff770a.PNG)

So I fixed another problem wheen looking for a solution for this one. 
I think the display call is missing but can't say why and where (I'm not fluent in Python)

**Comment by rendicott** [comment]
Closing since this is old. Reopen if needed.
