### ISSUE TITLE
Change to the group by function

### ISSUE THREAD

**Issue by Borrelworst** [rendicott/pySser#8]
Hi,

I am trying to generate a inventory file for Ansible and I am having the following issue: Generating the inventory file works just fine, but then I want to group hosts together (for example webservers, databases, etc.). The only way I get this to work, is in phpIPAM changing the Hostname field of a hosts to its function. Only then I get a correct group by. However, all of this is automatically discoverd, so I rather be able to group by something I can choose myself (for example description field, or a customfield that I add). 

Am I overlooking something, or can you maybe add this functionality to the script?

Thanks!

**Comment by rendicott** [comment]
The extra host var support is something I wanted to add back when I was using it for work. Right now all you can do is add custom fields and list them as host vars under the host IP entry. You can still only list each IP individually though. No grouping support was added.

I could take a stab at adding that functionality but I don't really have a test environment anymore. How badly do you need it?

You could always add a wrapper script that implements the ansible inventory script - - list method and calls the pySser script then takes all the hosts and groups them by a common host var and spits out json.

**Comment by Borrelworst** [comment]
Hi Rendicott,

Thanks for your quick reaction! I already tried to adjust the code but not yet a Python guru so I am struggling a little, especially finding out where to make the changes.

The original script works in such a way, that when I change the hostname on at least 2 hosts to the same name (for example webserver), I do get the following output:

"webserver": {
        "hosts": [
            "x.x.x.x", 
            "x.x.x.x"

So grouping works. I only do not want to group on the hostname but on the description. So I've create a new funtion called group_by_description, which does that. I can see that the output is right as it shows the IDs of servers which have the same description:

['12', '13']
['11', '18', '19', '20', '21', '22', '23', '24', '25']

However I am having troubles with print the correct output. I've changed the dictionary to print like this:
master_dict[description] = { 'hosts': addresses }
instead of:
master_dict[hname] = { 'hosts': addresses, 'vars': additional_vars }

 But it only outputs one element per description instead of all the elements with the same description.

Maybe you have a thought about where I am missing something

**Comment by Borrelworst** [comment]
I am a little more ahead now: I does show me all the correct number of hosts per description, however it shows the same host per description:

  "database": {
    "hosts": [
      "hostname1", 
      "hostname1"
    ]
  }, 
  "webserver": {
    "hosts": [
      "hostname2", 
      "hostname2"
]

The number of hosts is correct, but it only shows the last hostname from that group.

**Comment by Borrelworst** [comment]
Hi,

I've fixed the issue, apparently I had changed to much of the code, in the dump_ansible function I changed 

for ip in others:
                    addresses.append(ip)
to
for ip in others:
                    addresses.append(address.hostname_short)

which caused the duplicates. 
Now it works as expected, it groups on the description field.

**Comment by rendicott** [comment]
Closing issue. Open PR if you'd like to see your changes added permanently.
