### ISSUE TITLE
requests module dependency

### ISSUE THREAD

**Issue by mvernimmen** [rendicott/pySser#9]
Hi,

Not sure this is a problem with the requests module on my machine, or whether this is because perhaps os-x is not supported but this is what I'm getting when I try to run pysser:
```
$ ./pysser.py --list
Traceback (most recent call last):
  File "./pysser.py", line 16, in <module>
    import requests
ImportError: No module named requests

$ pip install requests
Requirement already satisfied: requests in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests)
You are using pip version 9.0.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$
```

Any pointer in the right direction would be much appreciated!

**Comment by rendicott** [comment]
Check the env header in `pysser.py` (e.g, `/usr/bin/env python`) . Make sure it's resolving to the correct version of python that has requests installed in your environment.

**Comment by mvernimmen** [comment]
thanks, turns out brew doesn't overwrite existing python on os-x and installs python 2 as python2, so I changed the header and now the script runs.
